spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog-default.sql
    enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}

server:
  port: ${PORT:8080}

logging:
  level:
    com.example.phonebook: WARN
    org.springframework: ERROR
    org.hibernate: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Security settings for production
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# Application custom properties
app:
  title: "Phonebook - Production"
