spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog-default.sql
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: ${BONSAI_URL}

server:
  port: ${PORT:8080}

logging:
  level:
    com.example.phonebook: INFO
    org.springframework: WARN
    org.hibernate: WARN
