spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog-default.sql
    enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: ${BONSAI_URL}

server:
  port: ${PORT:8080}

logging:
  level:
    com.example.phonebook: INFO
    org.springframework: WARN
    org.hibernate: WARN
